version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8623:5000"  # Nur localhost, Port 8623
    environment:
      - NODE_ENV=production
      - JWT_SECRET=konfi-secret-super-secure-2025
    volumes:
      - ./data:/app/data        # 🔄 GEÄNDERT: Lokaler Mount
      - ./uploads:/app/uploads  # 🔄 GEÄNDERT: Lokaler Mount
    restart: unless-stopped
